site_name: Swierk
site_url: https://sitename.example

nav:
  - Home: index.md
  - Installation:
      - Dependencies: Installation/dependencies.md
      - Docker Guide: Installation/docker.md
      - Environment Setup: Installation/environment.md
      - WSL Instructions: Installation/wsl.md
  - Database:
    - Migrations: Database/migrations.md
    - Models: Database/models.md
  - Tools:
    - Tools: Tools/tools.md
  - Business logic:
    - Business logic: Business logic/business logic.md
  - Tests: Tests/tests.md
  - Tutorial: Tutorial/tutorial.md
     
  
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
